# Copyright: Copyright (c) 2016-2017, Joakim Brännström. All rights reserved.
# License: http://www.boost.org/LICENSE_1_0.txt, Boost Software License 1.0
# Author: Joakim Brännström (joakim.brannstrom@gmx.com)

.PHONY: all

all: sleep0 sleep1

sleep0:
	sleep 120

sleep1:
	sleep 120
